// file: src/webview/main.ts
import { 
    provideVSCodeDesignSystem, 
    vsCodeBadge,
	vsCodeButton,
	vsCodeCheckbox,
	vsCodeDataGrid,
	vsCodeDataGridCell,
	vsCodeDataGridRow,
	vsCodeDivider,
	vsCodeDropdown,
	vsCodeLink,
	vsCodeOption,
	vsCodePanels,
	vsCodePanelTab,
	vsCodePanelView,
	vsCodeProgressRing,
	vsCodeRadioGroup,
	vsCodeRadio,
	vsCodeTag,
	vsCodeTextArea,
	vsCodeTextField
} from "@vscode/webview-ui-toolkit";

provideVSCodeDesignSystem().register(
    vsCodeBadge(),
	vsCodeButton(),
	vsCodeCheckbox(),
	vsCodeDataGrid(),
	vsCodeDataGridCell(),
	vsCodeDataGridRow(),
	vsCodeDivider(),
	vsCodeDropdown(),
	vsCodeLink(),
	vsCodeOption(),
	vsCodePanels(),
	vsCodePanelTab(),
	vsCodePanelView(),
	vsCodeProgressRing(),
	vsCodeRadioGroup(),
	vsCodeRadio(),
	vsCodeTag(),
	vsCodeTextArea(),
	vsCodeTextField()
    );